### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gibertgibs**
This could be a nice way to describe the readme file.

### CODE REVIEW

**Review by PyGamma — CHANGES_REQUESTED** [review]
Needed few additions, thought you are on the right path of using the read me file.

**Comment by gibertgibs** [comment]
Definitely yes...But I had to put it that way because...The maintainers of this project know best what is to be in the Readme file than I do....That's why I left it that way so that they can add the rest.

**Comment by gibertgibs** [comment]
Definitely yes...But I had to put it that way because...The maintainers of this project know best what is to be in the Readme file than I do....That's why I left it that way so that they can add the rest.

**Review by timmwille — COMMENTED** [review]
looks good, will add

**Pull request merged**
